### ISSUE TITLE
Fails to build with sundials-7.5.0

### ISSUE THREAD

**Issue by yurivict** [bjodah/pycvodes#149]
Errors:
```
In file included from pycvodes/_cvodes.cpp:810:
In file included from /usr/local/lib/python3.11/site-packages/numpy/core/include/numpy/arrayobject.h:5:
In file included from /usr/local/lib/python3.11/site-packages/numpy/core/include/numpy/ndarrayobject.h:12:
In file included from /usr/local/lib/python3.11/site-packages/numpy/core/include/numpy/ndarraytypes.h:1929:
/usr/local/lib/python3.11/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: "Using deprecated NumPy API, disable it with "          "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-W#warnings]
   17 | #warning "Using deprecated NumPy API, disable it with " \
      |  ^
In file included from pycvodes/_cvodes.cpp:812:
In file included from pycvodes/include/cvodes_cxx.hpp:37:
pycvodes/include/sundials_cxx.hpp:34:13: error: unknown type name 'realtype'; did you mean 'decltype'?
   34 |             realtype *get_data_ptr() const {
      |             ^~~~~~~~
      |             decltype
pycvodes/include/sundials_cxx.hpp:34:21: error: expected '(' after 'decltype'
   34 |             realtype *get_data_ptr() const {
      |                     ^
      |                     (
pycvodes/include/sundials_cxx.hpp:56:9: error: expected member name or ';' after declaration specifiers
   56 |         };
      |         ^
pycvodes/include/sundials_cxx.hpp:82:38: error: unknown type name 'realtype'; did you mean 'decltype'?
   82 |             Vector(long int n, const realtype * const data
      |                                      ^~~~~~~~
      |                                      decltype
pycvodes/include/sundials_cxx.hpp:82:46: error: expected '(' after 'decltype'
   82 |             Vector(long int n, const realtype * const data
      |                                              ^
      |                                              (
pycvodes/include/sundials_cxx.hpp:87:17: error: expected ')'
   87 |                 : VectorBase_(N_VNew_Serial(n
      |                 ^
pycvodes/include/sundials_cxx.hpp:82:19: note: to match this '('
   82 |             Vector(long int n, const realtype * const data
      |                   ^
pycvodes/include/sundials_cxx.hpp:111:14: error: expected ';' at end of declaration list
  111 |             }
      |              ^
      |              ;
pycvodes/include/sundials_cxx.hpp:80:19: error: no member named 'dump' in 'sundials_cxx::nvector_serial::Vector'
   80 |                 v.dump(get_data_ptr());
      |                 ~ ^
pycvodes/include/sundials_cxx.hpp:80:24: error: use of undeclared identifier 'get_data_ptr'
   80 |                 v.dump(get_data_ptr());
      |                        ^
pycvodes/include/sundials_cxx.hpp:120:36: error: unknown type name 'realtype'; did you mean 'decltype'?
  120 |             VectorView(long int n, realtype * const data
      |                                    ^~~~~~~~
      |                                    decltype
pycvodes/include/sundials_cxx.hpp:120:44: error: expected '(' after 'decltype'
  120 |             VectorView(long int n, realtype * const data
      |                                            ^
      |                                            (
pycvodes/include/sundials_cxx.hpp:125:17: error: expected ')'
  125 |                 : VectorBase_(N_VMake_Serial(n, const_cast<realtype*>(data)
      |                 ^
pycvodes/include/sundials_cxx.hpp:120:23: note: to match this '('
  120 |             VectorView(long int n, realtype * const data
      |                       ^
pycvodes/include/sundials_cxx.hpp:169:14: error: expected ';' at end of declaration list
  169 |             }
      |              ^
      |              ;
In file included from pycvodes/_cvodes.cpp:812:
pycvodes/include/cvodes_cxx.hpp:38:10: fatal error: 'cvodes/cvodes_spils.h' file not found
   38 | #include <cvodes/cvodes_spils.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~
1 warning and 14 errors generated.
```

The ```realtype``` type is defined in:
```
/usr/local/include/sundials/sundials_types_deprecated.h:typedef float realtype;
/usr/local/include/sundials/sundials_types_deprecated.h:typedef double realtype;
```

Version: 0.14.6
Python-3.11
FreeBSD 15 STABLE

**Comment by bjodah** [comment]
Yes, until someone patches in support for latest sundials the requirement is `sundials<7`.
